Doxy refactor
kipr/libwallaby pull request #173
Opened 2022-09-12 14:37 UTC by Zacharyprime

This is just the basic doxygen setup.

The page is purple for now because I couldn't find a red color that didn't look ugly in the output.
I think the purple looks good even if it's not KIPR colors. It is at least analogous to red.

2022-09-12 15:07 UTC, Zacharyprime commented
This makes the new documentation mostly complete.

We still need to change where harrogate targets to get the home page.
It should target the documentation/html/modules.html page.

We may end up wanting to set the doxygen output directory to something specific, but that will have to be done after Tim is finished with the OS

2022-09-12 20:17 UTC, bmcdorman requested changes

2022-09-12 20:17 UTC, bmcdorman commented on .gitignore
> +documenation/html
`documentation` is misspelled

2022-09-16 21:18 UTC, bmcdorman approved these changes

2022-09-16 21:18 UTC, merged